export const path = {
    home : '/',
    blog: '/blog',
    blogdetail:'/blogdetail/:id',
    shop:'/shop',
    products:'/products/:id',
    contact : '/contact',
    login:'/login',
    register:'/register',
    viewcart:'/viewcart',
    checkout:"/checkout",
    collections:"/collections",
    quickadd:"/quickadd",
    aboutus:"/aboutus",
    faqs:'/faqs',
    pagenotfound:"/pagenotfound",
    admin:"/admin",
    order:"/order",
}